component: scf
name: ap-guangzhou_default_Transcode
inputs:
  name: Transcode
  src:
    src: ./src
  runtime: Python3.6
  region: ap-guangzhou
  handler: index.main_handler
  memorySize: 3072
  timeout: 300
  environment:
    - key: region
      value: region of target bucket
    - key: target_bucket
      value: target bucket name
    - key: target_path
      value: path of target bucket
  triggers:
    - type: cos
      enable: true
      bucket: 
      events: 'cos:ObjectCreated:*'
