component: scf
name: ap-guangzhou_default_COSSCFCkafka
inputs:
  name: COSSCFCkafka
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python3.6
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 5
  environment:
    - key: kafka_address
      value: ckafka address
    - key: kafka_topic_name
      value: ckafka topic name
  triggers: 
    - type: cos                                    #COS触发器配置，选填，如模版代码运行依赖触发器则需要填写，会作为使用该模版创建函数时的默认触发器配置
      enable: true
      bucket: 
      events: 'cos:ObjectCreated:*' 
