component: scf
name: ap-guangzhou_helloworld_demo_php80
inputs:
  name: helloworld_demo_php80
  src:
    src: ./src
  type: web
  runtime: Php8.0
  namespace: default
  region: ap-guangzhou
  memorySize: 512
  timeout: 3
  triggers:
     - type: apigw
       name: SCF_API_SERVICE
       protocols:
        - http
        - https
       environment: release
       netTypes:
        - OUTER
       apis:
        - path: /
          method: ANY
