component: scf
name: ap-guangzhou_springboot_webfunc_java11
inputs:
  name: springboot_webfunc_java11
  src:
    src: ./src
  type: web
  runtime: Java11
  region: ap-guangzhou
  memorySize: 512
  timeout: 3
  triggers:
     - type: apigw
       name: SCF_API_SERVICE
       protocols:
        - http
        - https
       environment: release
       netTypes:
        - OUTER
       apis:
        - path: /
          method: ANY