app: nuxtjsAppName
stage: dev
component: nuxtjs
name: nuxtjsInstance
inputs:
  region: ap-guangzhou
  runtime: Nodejs10.15
  entryFile: sls.js
  src:
    src: ./
    dist: ./
    hook: npm run build
    exclude:
      - .env
      - node_modules/**
  layers:
    - name: layerName
      version: 1
  functionConf:
    timeout: 3
    eip: false
    memorySize: 128
  apigatewayConf:
    customDomains:
      - domain: abc.com
        certificateId: abcdefg
        isDefaultMapping: false
        pathMappingSet:
          - path: /
            environment: release
        protocols:
          - http
          - https
    protocols:
      - http
      - https
    environment: release
    serviceTimeout: 60
  staticConf:
    cosConf:
      bucket: static-bucket
      acl:
        permissions: public-read
      sources:
        - src: .nuxt/dist/client
          targetDir: /
        - src: static
          targetDir: /
    cdnConf:
      area: mainland
      domain: xxxx.xxx
      autoRefresh: true
      refreshType: delete
      forceRedirect:
        switch: on
        redirectType: https
        redirectStatusCode: 301
      https:
        http2: on
        certId: "abc"
