org: '1258710235'
app: generate-usersig
stage: prod
component: layer
name: generate-usersig-layer
inputs:
  name: generate-usersig-layer
  region: na-siliconvalley
  src:
    src: ../node_modules
    targetDir: /node_modules
  runtimes:
    - Nodejs12.16
