component: scf
name: ap-guangzhou_ciam_express_demo
inputs:
  name: ciamExpressDemo
  src:
    src: ./src
  type: web
  runtime: Nodejs12.16
  namespace: default
  region: ap-guangzhou
  memorySize: 512
  timeout: 3
  environment:    #CIAM环境变量，获取方法参考最佳实践文档链接
    variables:
      CLIENT_ID: your-clientid #此处为CIAM的应用ID，CIAM应用中获取
      USER_DOMAIN: your-userDomain #此处为租户域名，CIAM域名管理中获取
      REDIRECT_URI: your-redirectUri #此处为回调地址，CIAM应用管理中获取
      LOGOUT_REDIRECT_URL: your-logoutRedirectUrl #此处为退出回调地址，CIAM应用管理中获取
  triggers:
     - type: apigw
       name: SCF_API_SERVICE
       protocols:
        - http
        - https
       environment: release
       netTypes:
         - OUTER
       apis:
         - path: /
           method: ANY