component: scf
name: ap-guangzhou_default_SpringBoot
inputs:
  src:
    src: ./src
  region: ap-guangzhou
  name: SpringBoot
  runtime: Java8
  handler: com.tencent.scfspringbootjava8.ScfHandler::mainHandler
  memorySize: 512
  timeout: 30
  triggers:
    - type: apigw
      name: SCF_API_SERVICE
      protocols:
        - http
      environment: release
      apis:
        - path: /todos
          method: ANY
          function:
            isIntegratedResponse: true

