component: scf
name: ap-guangzhou_default_COSHashCalculate
inputs:
  src:
    src: ./src
  handler: index.main_handler
  memorySize: 256
  name: COSHashCalculate
  region: ap-guangzhou
  runtime: Nodejs12.16
  asyncRunEnable: TRUE
  traceEnable: TRUE
  timeout: 86400
