component: scf
name: ap-guangzhou_httpdns_sdnshook
inputs:
  name: SDNSook
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python3.6
  namespace: httpdns
  region: ap-guangzhou
  memorySize: 128
  timeout: 30
  triggers:                                         
    - type: apigw
      name: SCF_API_SERVICE
      protocols:
        - http
        - https
      environment: release
      netTypes:
        - INNER
      apis:
        - path: release/
          method: ANY
          function:
            isIntegratedResponse: false
            isBase64Encoded: false
