component: scf
name: ap-guangzhou_default_COSWorkflowFfmpegTranscode
inputs:
  src:
    src: ./src
  handler: index.main_handler
  memorySize: 1024
  name: COSWorkflowFfmpegTranscode
  region: ap-guangzhou
  runtime: Nodejs12.16
  asyncRunEnable: TRUE
  traceEnable: TRUE
  timeout: 86400
