component: scf
name: ap-guangzhou_default_CLSToElasticsearch
inputs:
  name: CLSToElasticsearch
  src:
    src: ./src
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 30
  environment:
    - key: ES_Address
      value: ES_Address
    - key: ES_User
      value: ES_User
    - key: ES_Password
      value: ES_Password
