app: springbootAppName
stage: dev 
component: springboot 
name: springbootInstance
inputs:
  region: ap-guangzhou 
  runtime: Java8
  src: ./
  projectJarName: 'my-springboot.jar'
  functionConf:
    handler: 'example.MyHandler::mainHandler'
    timeout: 30
    memorySize: 256
  apigatewayConf:
    customDomains:
      - domain: abc.com
        certificateId: abcdefg
        isDefaultMapping: false
        pathMappingSet:
          - path: /
            environment: release
        protocols:
          - http
          - https
    protocols:
      - http
      - https
    environment: release
    serviceTimeout: 60
