component: scf
name: ap-guangzhou_data_forwarding_demo_Go1
inputs:
  name: IoT Explorer data forwarding
  src:
    src: ./src
  type: web
  runtime: Go1
  namespace: default
  region: ap-guangzhou
  memorySize: 512
  timeout: 3
  triggers:
     - type: apigw
       name: SCF_API_SERVICE
       protocols:
        - http
        - https
       environment: release
       netTypes:
        - OUTER
       apis:
        - path: /
          method: ANY
