component: scf
name: ap-guangzhou_java_webfunc_mockserver_demo
inputs:
  name: java_webfunc_mockserver_demo
  src:
    src: ./src
  type: web
  runtime: Java8
  region: ap-guangzhou
  memorySize: 512
  timeout: 3
  triggers:
     - type: apigw
       name: SCF_API_SERVICE
       protocols:
        - http
        - https
       environment: release
       netTypes:
        - OUTER
       apis:
        - path: /
          method: ANY
