app: ApiGWOauthAppName
stage: dev
component: flask
name: oatuhFlaskInstance
inputs:
  region: ap-guangzhou
  runtime: Python3.6
  src:
    hook: pip3 install -r requirements.txt -t ./
    dist: ./
    exclude:
      - .env
  functionConf:
    timeout: 3
    eip: false
    memorySize: 128
  apigatewayConf:
    serviceTimeout: 60
    protocols:
      - http
      - https
    environment: release
