component: scf
name: ap-guangzhou_default_COSSyncData
inputs:
  src:
    src: ./src
  region: ap-guangzhou
  name: COSSyncData
  runtime: Java8
  handler: com.example.MainHandler::mainHandler
  memorySize: 512
  timeout: 59
  environment:
    - key: SOURCE_SECRET_ID
      value: source appid secretid
    - key: SOURCE_SECRET_KEY
      value: source appid secretkey
    - key: SOURCE_REGION
      value: source bucket region
    - key: TARGET_SECRET_ID
      value: target appid secretid
    - key: TARGET_SECRET_KEY
      value: target appid secretkey
    - key: TARGET_REGION
      value: target bucket region
    - key: TARGET_BUCKET
      value: target bucket name(xxx-appid)

